### ISSUE TITLE
Dead argument for format() function

### ISSUE THREAD

**Issue by jakkdu** [angr/heaphopper#4]
Hi, [This line](https://github.com/angr/heaphopper/blob/master/heaphopper/analysis/tracer/tracer.py#L603) does not use its argument.

The original code is
```python
logger.info('Creating vuln descriptions'.format(desc_file))
```

My guess is that it should be
```python
logger.info('Creating vuln descriptions: {}-desc.yaml'.format(desc_file))
```

or 

```python
logger.info('Creating vuln descriptions')
```

But I don't know which one is your intention.

**Comment by m1ghtym0** [comment]
Thank you @jakkdu
